// orchestrator.js — exercise the FULL runJob (prepare -> transcribe -> clean -> build)
// against the fixtures, the same interleaving the app uses. This catches bugs the
// piecemeal integration test misses (e.g. NLM's tab cleanup closing the Gemini tab).
const assert = require('assert');
const os = require('os'), path = require('path'), fs = require('fs');
const { spawnSync } = require('child_process');
const sel = require('../src/main/selectors');
const { start } = require('./fixtures/server');
const { Orchestrator } = require('../src/main/pipeline/orchestrator');

(async () => {
  // a real short audio for the prepare stage (generated by the test runner)
  const audio = process.argv[2] || '/tmp/kateb-tone.mp3';
  if (!fs.existsSync(audio)) { spawnSync(require('ffmpeg-static'), ['-y', '-v', 'error', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2', '-c:a', 'libmp3lame', audio]); }
  assert(fs.existsSync(audio), 'test audio missing: ' + audio);

  const srv = await start();
  sel.notebooklm.home = srv.base + '/';
  sel.notebooklm.notebookUrl = (id) => srv.base + '/notebook/' + id;
  sel.gemini.home = srv.base + '/gemini';

  const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'kateb-orch-'));
  // reuse the already-installed browser (avoid a 150MB download in provision)
  try { fs.symlinkSync(path.join(os.homedir(), '.cache', 'ms-playwright'), path.join(userData, 'ms-playwright'), 'dir'); } catch (_) {}
  process.env.KATEB_HEADLESS = '1';

  const config = require('../src/main/config').defaults();
  config.output.dir = path.join(userData, 'out');
  config.throttleMs = 30;
  config.chunkWords = 200; // force multiple chunks through Gemini

  const events = [];
  const orch = new Orchestrator({ userDataDir: userData, config, emit: (e) => events.push(e) });
  const job = { id: 'f1', path: audio, meta: { title: 'سندِ تست', date: '۱۴۰۵/۰۱/۰۱' } };

  await orch.runJob(job);
  await orch.shutdown();
  await srv.close();

  const err = events.find((e) => e.type === 'file-error');
  if (err) { console.error('file-error:', err.error); process.exit(1); }
  const done = events.find((e) => e.type === 'file-done');
  assert(done, 'file-done should be emitted');
  assert(done.outputs && done.outputs.length, 'outputs should be written');
  for (const p of done.outputs) assert(fs.existsSync(p) && fs.statSync(p).size > 0, 'output non-empty: ' + p);
  const stages = events.filter((e) => e.type === 'stage' && e.status === 'done').map((e) => e.stage);
  console.log('stages done:', [...new Set(stages)].join(' -> '));
  console.log('outputs:', done.outputs.map((p) => path.basename(p)).join(', '));
  console.log('\nORCHESTRATOR TEST PASSED ✓');
})().catch((e) => { console.error('ORCH TEST FAILED:', e.stack || e); process.exit(1); });
